#!/bin/bash

# Startup progs
sxhkd &
compton --experimental-backends -b &
polybar watch &
polybar watch2 &
nitrogen --restore &
xsetroot -cursor_name left_ptr &

firefox &
discord &
discord-ptb &
spotify &

# Display setup	
bspc monitor DisplayPort-0 -d I II III IV
bspc monitor DisplayPort-1 -d I II III IV

bspc config active_border_color   \#2a2a2a
bspc config focused_border_color  \#2a2a2a
bspc config normal_border_color   \#2a2a2a
bspc config focus_follows_pointer true

gap1=6
gap2=6

bspc config top_padding          38
bspc config left_padding         $gap1
bspc config right_padding        $gap1
bspc config bottom_padding       $gap1

bspc config border_width         1.0
bspc config window_gap           $gap2

bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
	
# Program order
bspc rule -a Yad state=floating
bspc rule -a Firefox border=off desktop='DisplayPort-1:^1'
bspc rule -a discord state=floating border=off desktop='DisplayPort-0:^3'
bspc rule -a Alacritty border=on
