#!/bin/bash

# Startup progs
sxhkd 2>&1 | tee ~/.sxhkd.log &
compton --config ~/.config/compton/compton.conf -b &
polybar watch &
polybar watch2 &
nitrogen --restore &
xsetroot -cursor_name left_ptr &

firefox &
discord &
discord-canary &
spotify &

# Display setup	
#bspc monitor DP-0 -d    
bspc monitor DP-0 -d I II III IV
bspc monitor DVI-I-0 -d I II III IV

bspc config active_border_color   \#752a2a
bspc config focused_border_color  \#752a2a
bspc config normal_border_color   \#752a2a
bspc config focus_follows_pointer true
bspc config border_width         0
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
	
# Program order
bspc rule -a Yad state=floating
bspc rule -a Firefox border=off desktop='DVI-I-0:^1'
bspc rule -a discord state=floating border=off desktop='DP-0:^3'
bspc rule -a Alacritty border=off
bspc rule -a Spotify state=floating desktop='DVI-I-0:^2'
