# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
#env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: xterm-256color

window:
  dynamic_padding: false
  padding:
    x: 0
    y: 4

# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: Fira Mono
    style: Medium

  # The bold font face
  bold:
    family: Fira Mono

  # The italic font face
  italic:
    family: Fira Mono

  # Point size of the font
  size: 11.0

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: false

# Colors (Undead)
colors:
  primary:
    background: '0x1b1b1b'
    foreground: '0x9e9e9e'

  normal:
    black:   '0x1b1b1b'
    red:     '0xac4142'
    green:   '0x90a959'
    yellow:  '0xf4bf75'
    blue:    '0x6a9fb5'
    magenta: '0xaa759f'
    cyan:    '0x75b5aa'
    white:   '0x616161'

  bright:
    black:   '0x262626'
    red:     '0x752a2a'
    green:   '0x5d742a'
    yellow:  '0x754e2a'
    blue:    '0x2a4e74'
    magenta: '0x703664'
    cyan:    '0x297366'
    white:   '0x9e9e9e'

mouse:
  url:
    launcher: firefox

cursor:
    style: Underline
